
import Navigation from './components/Navigation/navigation';
import './globals.css';

import { Providers } from '@/redux/provider';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
        <Providers>
      <body className="h-full w-full bg-grey-400 bg-body bg-cover bg-no-repeat">
       <Navigation/>
        <hr className="mb-4 ml-[94px] border-prime-200 border-opacity-50 md:mx-[93px] md:my-6" />

        <main className="h-full w-full pb-[100px] lg:px-[93px]">
        {children}
        </main>
      </body>
      </Providers>
    </html>
  );
}

