import { Button } from "@/ui/Button";
import { ArrowLongLeftIcon } from "@heroicons/react/24/outline";
import Link from "next/link";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="mb-[50px] flex w-full justify-start">
        <Button href="/" variant="plain">
          <ArrowLongLeftIcon className="h-4 w-4" /> Back
        </Button>
        <aside className="fixed z-40 w-[258px] h-full">
          <ul className="w-full h-full p-5 gap-2.5 flex items-start flex-col">
           <li>
            <Link href="/" className="" ></Link>
           </li>
          </ul>
        </aside>
          {/* <main className="h-full w-full pb-[100px] lg:px-[93px]">{children}</main> */}
       
      </div>
    </>
  );
}
