import { Button } from '@/ui/Button';
import { ArrowLongLeftIcon } from '@heroicons/react/24/outline';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const SideLink = ({ href, title }: { href: string; title: string }) => (
  <Link
    href={href}
    className="flex w-[218px] items-start gap-2.5 border-b border-grey-200 bg-grey-300 p-5 font-rob text-[16px]/[25px] font-bold text-white"
  >
    {title}
  </Link>
);

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="mb-[20px] flex w-full justify-start">
        <Button href="/" variant="plain">
          <ArrowLongLeftIcon className="h-4 w-4" /> Back to Homepage
        </Button>
      </div>
      <div className="flex w-full items-start gap-[47px]">
        <aside className="z-40 h-full w-[258px]">
          <ul className="flex h-full w-full flex-col items-start gap-2.5 p-5">
            <li>
              <SideLink href="/" title="My projects" />
            </li>
            <li>
              <SideLink href="/" title="Loan schedule" />
            </li>
            <li>
              <SideLink href="/" title="Oldest" />
            </li>
          </ul>
        </aside>
        <main className="relative  h-full w-full">{children}</main>
      </div>
    </>
  );
}
